// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var Engine, bufferify, iced, os, run, set_log, spawn, stream, __iced_k, __iced_k_noop, _log;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  spawn = require('child_process').spawn;

  stream = require('./stream');

  os = require('os');

  _log = function(x) {
    return console.warn(x.toString('utf8'));
  };

  exports.set_log = set_log = function(log) {
    return _log = log;
  };

  exports.Engine = Engine = (function() {
    function Engine(_arg) {
      this.args = _arg.args, this.stdin = _arg.stdin, this.stdout = _arg.stdout, this.stderr = _arg.stderr, this.name = _arg.name, this.opts = _arg.opts;
      this.stderr || (this.stderr = new stream.FnOutStream(_log));
      this.stdin || (this.stdin = new stream.NullInStream());
      this.stdout || (this.stdout = new stream.NullOutStream());
      this.opts || (this.opts = {});
      this._exit_code = null;
      this._exit_cb = null;
      this._err = null;
      this._n_out = 0;
    }

    Engine.prototype._spawn = function() {
      var args, name;
      args = this.args;
      name = this.name;
      if (os.platform() === 'windows') {
        args = [name, "/c", "/s"].concat(args);
        name = "cmd";
      }
      return this.proc = spawn(name, args, this.opts);
    };

    Engine.prototype.run = function() {
      this._spawn();
      this.stdin.pipe(this.proc.stdin);
      this.proc.stdout.pipe(this.stdout);
      this.proc.stderr.pipe(this.stderr);
      this.pid = this.proc.pid;
      this._n_out = 3;
      this.proc.on('exit', (function(_this) {
        return function(status) {
          return _this._got_exit(status);
        };
      })(this));
      this.proc.stdout.on('end', (function(_this) {
        return function() {
          return _this._got_eof();
        };
      })(this));
      this.proc.stderr.on('end', (function(_this) {
        return function() {
          return _this._got_eof();
        };
      })(this));
      this.proc.on('error', (function(_this) {
        return function(err) {
          return _this._got_error(err);
        };
      })(this));
      return this;
    };

    Engine.prototype._got_exit = function(status) {
      --this._n_out;
      this._exit_code = status;
      this.proc = null;
      this.pid = -1;
      return this._maybe_call_callback();
    };

    Engine.prototype._got_error = function(err) {
      this._err = err;
      this.proc = null;
      this.pid = -1;
      return this._maybe_call_callback();
    };

    Engine.prototype._got_eof = function() {
      --this._n_out;
      return this._maybe_call_callback();
    };

    Engine.prototype._can_finish = function() {
      return (this._err != null) || (this._n_out <= 0 && (this._exit_code != null));
    };

    Engine.prototype._maybe_call_callback = function() {
      var cb;
      if ((this._exit_cb != null) && this._can_finish()) {
        cb = this._exit_cb;
        this._exit_cb = null;
        return cb(this._err, this._exit_code);
      }
    };

    Engine.prototype.wait = function(cb) {
      this._exit_cb = cb;
      return this._maybe_call_callback();
    };

    return Engine;

  })();

  exports.bufferify = bufferify = function(x) {
    if (x == null) {
      return null;
    } else if (typeof x === 'string') {
      return new Buffer(x, 'utf8');
    } else if (Buffer.isBuffer(x)) {
      return x;
    } else {
      return null;
    }
  };

  exports.run = run = function(inargs, cb) {
    var args, b, def_out, eklass, err, name, opts, out, quiet, rc, stderr, stdin, stdout, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    args = inargs.args, stdin = inargs.stdin, stdout = inargs.stdout, stderr = inargs.stderr, quiet = inargs.quiet, name = inargs.name, eklass = inargs.eklass, opts = inargs.opts;
    if ((b = bufferify(stdin)) != null) {
      stdin = new stream.BufferInStream(b);
    }
    if (quiet) {
      stderr = new stream.NullOutStream();
    }
    if (stdout == null) {
      def_out = true;
      stdout = new stream.BufferOutStream();
    } else {
      def_out = false;
    }
    err = null;
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/max/src/iced-spawn/src/cmd.iced"
        });
        (new Engine({
          args: args,
          stdin: stdin,
          stdout: stdout,
          stderr: stderr,
          name: name,
          opts: opts
        })).run().wait(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return rc = arguments[1];
            };
          })(),
          lineno: 116
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        if ((err == null) && (rc !== 0)) {
          eklass || (eklass = Error);
          err = new eklass("exit code " + rc);
          err.rc = rc;
        }
        out = def_out != null ? stdout.data() : null;
        return cb(err, out);
      };
    })(this));
  };

}).call(this);
